### ISSUE TITLE
Sort inverts itself when reloading data.

### ISSUE THREAD

**Issue by clementdevos** [pbeshai/react-taco-table#27]
Hello, 

Looks like the sort is broken, when the data is reloaded, the sort order is inverted (ASC-> desc, desc -> asc) or am i missing something?

We have set a default sort on the first column, splitting the label value to sort on numbers. 

Or on other columns, we sort the data, change the values and the sort is either reseted or inverted.

Any ideas?
Cheers.

**Comment by pbeshai** [comment]
Thanks, I'll take a look.

**Comment by pbeshai** [comment]
Can confirm this is a bug. Fixing it now.

**Comment by clementdevos** [comment]
You're the best, thx a lot !

**Comment by pbeshai** [comment]
Will be posting to npm shortly

**Comment by pbeshai** [comment]
Fixed in v0.3.0

**Comment by clementdevos** [comment]
Sweet thanks!

**Comment by clementdevos** [comment]
Hey @pbeshai ,i'm still having this problem. 

Default sort is on **A** Column ASC
I change the sort to the **B** column (defaultSort : DESC)
Change the data, the sort stays on the **B** but is inverted (new order : ASC). 
Change the data again, the sort stays ASC on the **B** column

**Comment by clementdevos** [comment]
I need to refactor our data generation before going any further.

**Comment by pbeshai** [comment]
Thanks for letting me know. I'll try to reproduce in a bit

**Comment by clementdevos** [comment]
Yeah i think it's still buggy. I've simplified our data structure but it stills reverts to an ASC sorting when reloading the data.

**Comment by pbeshai** [comment]
Yep I think I've got it now. Put my keep direction check in the wrong place.

**Comment by pbeshai** [comment]
Ok should be fixed in v0.3.1

**Comment by clementdevos** [comment]
Confirmed fix!  Thanks!
